###########
# site.title, site.author.name

title:  Strange Case of Dr. Jekyll and Mr. Hyde
baseurl: "/jekyll-book-theme"
author:
  name: Robert Louis Stevenson


########
# more settings

collections:
  chapters:
      output: true

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"

markdown: kramdown

kramdown:
  auto_ids: true


sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md

plugins:
  - jekyll-redirect-from

lsi: false
